#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

	exclude = ["change_url"]
	test_upgrade_from.0791c817a74f1c18c1d14f6be2d27b92ba0a5960.name = "Upgrade from 1.6.27~1"
