#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

	exclude = ["change_url"]
	test_upgrade_from.44aae031d3be46874fce860a54ad6cd5400b0a22.name = "Upgrade from 1.7.7"
