#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-celery" --action="stop"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app-celery >/dev/null; then
	yunohost service remove $app-celery
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_safe_rm "/etc/crontab.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"