#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Federated forum and link aggregator" --log="/var/log/$app/$app.log"

ynh_restore "/etc/systemd/system/$app-celery.service"
systemctl enable "$app-celery.service" --quiet
yunohost service add "$app-celery" --description="Celery daemon for $app" --log="/var/log/$app-celery/celery.log"

ynh_config_add_systemd --service=$app-notifs --template=piefed-notifs.service
yunohost service add "$app-notifs" --description="Push notifications daemon for $app" --log="/var/log/$app-notifs/notifs.log"
ynh_config_add_logrotate "/var/log/$app-notifs/notifs.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/cron.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"
ynh_restore "/var/log/$app-celery/"

#=================================================
# RESTORE PERMISSIONS
#=================================================

chown -R $app:$app "$install_dir"
chown $app:www-data "$install_dir"
chown $app:www-data "$install_dir/app"
chown -R $app:www-data "$install_dir/app/static"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-notifs" --action="start"
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
