#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Federated forum and link aggregator" --log="/var/log/$app/$app.log"

ynh_restore "/etc/systemd/system/$app-celery.service"
systemctl enable "$app-celery.service" --quiet
yunohost service add "$app-celery" --description="Celery daemon for $app" --log="/var/log/$app-celery/$app.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"
ynh_restore "/var/log/$app-celery/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"