#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping a systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-celery" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace=".env celery_worker.py celeryd gunicorn.conf.py"

chown -R $app:$app "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Federated forum and link aggregator" --log="/var/log/$app/$app.log"
ynh_config_add_logrotate

ynh_config_add_systemd --service=$app-celery --template=celery
yunohost service add "$app-celery" --description="Celery daemon for $app"
ynh_config_add_logrotate "/var/log/$app-celery"

#=================================================
# UPDATE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Updating PostgreSQL database..."

myynh_update_psql_db

myynh_set_default_psql_cluster_to_debian_default

#=================================================
# UPGRADE APP
#=================================================
ynh_script_progression "Upgrading $app..."

pushd $install_dir
  venv/bin/pip3 install --upgrade -r requirements.txt
  venv/bin/pip3 install --upgrade gunicorn
  venv/bin/flask db migrate -m "users table"
  venv/bin/flask db upgrade
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
