#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-celery" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="venv .env celery_worker.py celeryd gunicorn.conf.py"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Federated forum and link aggregator" --log="/var/log/$app/$app.log"
ynh_config_add_logrotate

ynh_config_add_systemd --service=$app-celery --template=celery.service
yunohost service add "$app-celery" --description="Celery daemon for $app" --log="/var/log/$app-celery/celery.log"
ynh_config_add_logrotate "/var/log/$app-celery"

ynh_config_add_logrotate "$install_dir/logs/"

#=================================================
# UPGRADE APP
#=================================================
ynh_script_progression "Upgrading $app..."

pushd $install_dir
  ynh_hide_warnings venv/bin/pip3 install --upgrade -r requirements.txt
  ynh_hide_warnings venv/bin/pip3 install --upgrade gunicorn
  ynh_hide_warnings venv/bin/flask db migrate -m "users table"
  ynh_hide_warnings venv/bin/flask db upgrade
popd

chown -R $app:$app "$install_dir"
chown $app:www-data "$install_dir"
chown $app:www-data "$install_dir/app"
chown -R $app:www-data "$install_dir/app/static"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
